### ISSUE TITLE
T2RA 03 - Práctica 3 Implementación Animación

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-team-project-ra#1]
**Anexo reporte de práctica**

[T2RA 03 - Práctica 3 Implementación Animación.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-team-project-ra/files/11122804/T2RA.03.-.Practica.3.Implementacion.Animacion.pdf)

**Anexo rúbrica**

[Rúbrica reporte de practica 3.docx](https://github.com/SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-team-project-ra/files/11122807/Rubrica.reporte.de.practica.3.docx)

**Comment by CxrlosMX** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
